import dash_bootstrap_components as dbc


themes_list = [
    "BOOTSTRAP",
    "CYBORG",
    "DARKLY",
    "SLATE",
    "SOLAR",
    "SUPERHERO",
    "CERULEAN",
    "COSMO",
    "FLATLY",
    "JOURNAL",
    "LITERA",
    "LUMEN",
    "LUX",
    "MATERIA",
    "MINTY",
    "PULSE",
    "SANDSTONE",
    "SIMPLEX",
    "SKETCHY",
    "SPACELAB",
    "UNITED",
    "YETI",
]



themes = [dbc.DropdownMenuItem("BOOTSTRAP"),
dbc.DropdownMenuItem("CYBORG"),
dbc.DropdownMenuItem("DARKLY"),
dbc.DropdownMenuItem("SLATE"),
dbc.DropdownMenuItem("SOLAR"),
dbc.DropdownMenuItem("SUPERHERO"),
dbc.DropdownMenuItem("CERULEAN"),
dbc.DropdownMenuItem("COSMO"),
dbc.DropdownMenuItem("FLATLY"),
dbc.DropdownMenuItem("JOURNAL"),
dbc.DropdownMenuItem("LITERA"),
dbc.DropdownMenuItem("LUMEN"),
dbc.DropdownMenuItem("LUX"),
dbc.DropdownMenuItem("MATERIA"),
dbc.DropdownMenuItem("MINTY"),
dbc.DropdownMenuItem("PULSE"),
dbc.DropdownMenuItem("SANDSTONE"),
dbc.DropdownMenuItem("SIMPLEX"),
dbc.DropdownMenuItem("SKETCHY"),
dbc.DropdownMenuItem("SPACELAB"),
dbc.DropdownMenuItem("UNITED"),
dbc.DropdownMenuItem("YETI")]